version: "3.8"

services:

  mongodb:
    build: 
      context: ../Learn-Database
      dockerfile: Dockerfile
    container_name: mongo
    volumes:
      - ../Learn-Database/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: node_user
      MONGO_INITDB_ROOT_PASSWORD: learn123
      MONGO_INITDB_DATABASE: learn_db
    # ports:
    #   - "27017:27017"
    restart: on-failure

  mongo-express:
    image: mongo-express:0.54
    depends_on: 
      - mongodb
    ports: 
      - "8484:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: node_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: learn123
    restart: always

#   redis:
#     image: redis:3.2-alpine

  node:
    build: 
      context: ../LearnStudio-Back/learn-studio-api
      dockerfile: Dockerfile.dev
    depends_on:
      - mongodb
    #   - redis
    restart: on-failure
    ports:
      - 3000
    # environment:
    #     DATABASE_URL: 'postgres://node_user:node_password@postgres:5432/learn_db'
    #   REDIS_HOST: 'redis:6379'
    volumes:
      - ../LearnStudio-Back/learn-studio-api:/app

  angular:
    build:
      context: ../LearnStudio-Front
      dockerfile: Dockerfile.dev
    depends_on:
      - node
#      - redis
    restart: on-failure
    ports:
      - 80
    environment:
        BACKEND_INTERNAL_HOST: 'node:3000'
        BACKEND_EXTERNAL_HOST: 'http://learn-studio-api.test:8181'
        #   REDIS_HOST: 'redis:6379'
    volumes: 
      - ../LearnStudio-Front/learnstudio:/app

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - node
      - angular
    restart: on-failure
    ports:
      - 8181:80
      - 4443:443
    # volumes:
    #   - ./nginx/conf:/etc/nginx
    #   - ./nginx/certs:/etc/ssl/private
