version: "3.8"

services:

  mongo:
    build:
      context: ./Learn-Database
      dockerfile: Dockerfile


  mongo-express:
    image: mongo-express:0.54

  node:
    build:
      context: ./Learn-Back/learn-studio-api
      dockerfile: Dockerfile.dev

  angular:
    build:
      context: ./Learn-Front/learn-studio-front
      dockerfile: Dockerfile.dev

