version: "3.8"

services:

  mongodb:
    build:
      context: ./Learn-Database
      dockerfile: Dockerfile
    container_name: mongodb
    volumes:
      - ./Learn-Database/data:/data/db
      - ./Learn-Database/fixtures:/data/fixtures

    environment:
      MONGO_INITDB_ROOT_USERNAME: node_user
      MONGO_INITDB_ROOT_PASSWORD: learn123
      MONGO_INITDB_DATABASE: learn_db
    ports:
      - 27017:27017
    restart: on-failure

  mongo-express:
    image: mongo-express:0.54
    depends_on:
      - mongodb
    ports:
      - "8484:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: node_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: learn123
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: always

  node:
    build:
      context: ./Learn-Back/learn-studio-api
      dockerfile: Dockerfile.dev
    container_name: node
    depends_on:
      - mongodb
    restart: on-failure
    ports:
      - 3000
    environment:
      MONGODB_URL: mongodb://node_user:learn123@mongodb:27017/learn_db?authSource=admin&readPreference=primary&ssl=false
      PORT: 3000
      JWT_KEY: YOLO
    volumes:
      - ./Learn-Back/learn-studio-api:/app

  angular:
    build:
      context: ./Learn-Front/learnstudio
      dockerfile: Dockerfile.dev
    container_name: angular
    depends_on:
      - node
    restart: on-failure
    ports:
      - 80
    environment:
      BACKEND_INTERNAL_HOST: 'http://node:3000'
      BACKEND_EXTERNAL_HOST: 'http://learn-studio-api.test:8181'
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./Learn-Front/learnstudio:/home/node/app

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - node
      - angular
    restart: on-failure
    ports:
      - 8181:80
      - 4443:443
    volumes:
      - ./nginx/certs:/etc/ssl/private